language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli@~0.1.9
  - node_modules/.bin/bower install
after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
